
from ..error import InternalError
Error = InternalError